DELIMITER $$

CREATE TRIGGER VALIDA_SALDO
AFTER INSERT ON MOVIMIENTO
FOR EACH ROW
BEGIN
    DECLARE cuenta_saldo DECIMAL(10, 2);

    SELECT SALDO INTO cuenta_saldo FROM CUENTA WHERE IDTARJETA = NEW.IDTARJETA;

    IF cuenta_saldo - NEW.CANTIDAD >= 0 THEN
        UPDATE CUENTA
		SET saldo = saldo - NEW.cantidad
		WHERE idTarjeta = NEW.idTarjeta;
    END IF;
END$$

DELIMITER ;
/*DROP trigger VALIDA_SALDO; PARA MODIFICAR UN TRIGGER ES NECESARIO ELIMINARLO PRIMERO*/